added copy password to clipboard for `add` and `generate` commands
SonuBardai/lockbox pull request #34
Opened 2023-08-04 14:00 UTC by Manikya-Sharma

This is related to Issue #31 .
I have used `clipboard` crate to copy the password to clipboard.

In case the clipboard is unavailable, default approach to only present the password is used.

While generating multiple passwords, no password is copied to clipboard.

2023-08-04 15:46 UTC, SonuBardai commented on src/cli/commands.rs
>  pub fn add_password(
The password passed to `add_password` can either be randomly generated, or it can be a value passed through the `--password` flag. I think the way we're pushing data into the add command here is a bit ambiguous. Nothing that blocks this PR though, I think we can address it in a separate issue.

2023-08-04 16:22 UTC, SonuBardai requested changes
I think we should handle errors gracefully here. Think of it like: The main operation being performed here is Adding the password to the store, or Generating a new password. Copying to clipboard is a feature that's great if it works, but it shouldn't cause a panic to the main operation.

2023-08-04 16:22 UTC, SonuBardai commented on src/cli/commands.rs
> +            ctx.set_contents(password.to_owned()).unwrap();
I don't think we should be using `unwrap` here. The error handling behavior should be: either copy to clipboard if possible, if it's not possible and if there's an error then don't copy to clipboard and continue execution. Maybe print an error message like "Failed to copy to clipboard". Doing unwrap will just cause a panic and the actual operation (ie. adding the password to the store) wouldn't occur.

2023-08-04 16:24 UTC, Manikya-Sharma commented on src/cli/commands.rs
> +            ctx.set_contents(password.to_owned()).unwrap();
Understood, I will change that.

2023-08-06 15:57 UTC, SonuBardai reviewed
This looks good overall, I think there's one abstraction that is possible here that can be addressed within this PR.

2023-08-06 15:57 UTC, SonuBardai commented on src/cli/commands.rs
> +        let ctx_result: Result<ClipboardContext, _> = ClipboardProvider::new();
Would it be a good idea to isolate the copy to clipboard logic into it's own function? I think this will make the code more testable, keep the operations DRY, and also it's going to improve readability. I'm thinking of something like this:

```rust
fn copy_to_clipboard(text) -> anyhow::Result<()> {
    ...
}

if copy_to_clipboard(password).is_ok() { ... } else { ... } // or however we want to handle this Result
```

2023-08-06 16:52 UTC, SonuBardai commented
Also, please try pulling main now. The dependencies issue is resolved (https://github.com/SonuBardai/lockbox/pull/38) and the CI workflows should finish building on this PR 👍

2023-08-07 02:40 UTC, Manikya-Sharma commented on src/cli/commands.rs
> +        let ctx_result: Result<ClipboardContext, _> = ClipboardProvider::new();
That seems to be a good idea. I will implement that.

2023-08-07 15:25 UTC, SonuBardai approved these changes
Looks good! Thanks @Manikya-Sharma. Can you please pull main and resolve the conflicts so I can merge this in.

2023-08-08 03:07 UTC, merged