add_password unit test cases added
SonuBardai/lockbox pull request #37
Opened 2023-08-06 06:02 UTC by postmeback

Fixes #11 

Please review the code and let me know, if any changes required

2023-08-07 05:46 UTC, postmeback commented
I did `cargo fmt`. Can you have a look ?

2023-08-07 07:00 UTC, SonuBardai requested changes
The test needs to load passwords (ie. read the newly created store, decrypt it's contents), and then add a new password to it. This is the workflow of the password store. Apologies for not having any documentation on this, creating a new issue out of this for documenting how the password store works. For now we have a [README](https://github.com/SonuBardai/lockbox/blob/main/src/store/README.md) explaining how the encryption workflow functions.

2023-08-07 07:00 UTC, SonuBardai commented on src/store/mod.rs
> +        );
I think we can make this test parametrized using [rstest](https://crates.io/crates/rstest). For reference you can check out the tests for [`test_find_password`](https://github.com/SonuBardai/lockbox/blob/main/src/store/mod.rs#L208-L293), [`test_load_after_store_passwords`](https://github.com/SonuBardai/lockbox/blob/main/src/store/mod.rs#L152-L206). The benefit is that we can have multiple test cases, test various edge cases like passing empty password, empty username, empty service, etc. and have them run as individual tests, instead of having this one singular test case running for the functionality.

2023-08-07 13:56 UTC, postmeback commented on src/pass/mod.rs
> +    }
Your function will be much better because in this case, we will not be exposing the password, only the boolean result. I don't want the password field to be public.

2023-08-07 14:02 UTC, postmeback commented on src/store/mod.rs
> +// Rest of the code for crypto, pass, and other modules
Removed

2023-08-07 15:12 UTC, postmeback commented on src/store/mod.rs
> +            .unwrap();
Updated

2023-08-07 15:12 UTC, postmeback commented on src/store/mod.rs
> +        );
`rstest` does not work with test methods that take mutable state (like &mut self or &mut variables) as arguments. Since `test_add_password` method requires modifying the PasswordStore instance, it cannot be directly parameterized using rstest in the way I described.

2023-08-08 03:08 UTC, SonuBardai commented
@postmeback Feel free to rerequest for review when this is ready 👍

2023-08-09 04:24 UTC, SonuBardai commented on src/store/mod.rs
> +        );
Is there a compilation error that you're seeing when you create parametrized tests? @postmeback

2023-08-16 06:57 UTC, postmeback commented on src/store/mod.rs
> +        );
No, I asked chatgpt, whether i can use `rstest` for the given scenario. The result cam out from there.

2023-08-17 03:46 UTC, SonuBardai commented on src/store/mod.rs
> +        );
Cool. I've written several parametrized tests for methods that take mutable references to self, you can check them out here if you're interested. https://github.com/SonuBardai/lockbox/blob/main/src/store/mod.rs#L129

Eitherway, if you're still having trouble with it then we can deal with it in a separate issue. For now, we don't want to make the `password` field public like we've discussed in this comment https://github.com/SonuBardai/lockbox/pull/37#discussion_r1285411317. Also, I've refactored the code quite a bit, so that's where the conflicts are coming from. I might have renamed this `add_password` function to `push`, since it's a little more readable to do something like this:
```rs
PasswordStore::new().load().push("new_password").store();
```

2023-09-24 06:09 UTC, closed without merging